### ISSUE TITLE
Change from single module to multi module solution

### ISSUE THREAD

**Issue by ajoz** [ajoz/fp-workshop-jvm#2]
Currently we have the whole workshop as a one project with one module. I thought about splitting the content into several separate modules:
- java-exercises
- java-solutions
- java-tools
- kotlin-exercises
- kotlin-solutions
- kotlin-tools

We could compile them separately and partially verify everything is ok through circle CI or travis.

Either this or split the project per JVM language.
- java
-- fp-exercies
-- fp-solutions
-- fp-tools
- kotlin
-- fp-exercises
-- fp-solutions
-- fp-tools

**Comment by ajoz** [comment]
We've decided to to use the schema:
* java
  -- exercises
  -- solutions
  -- tools

* kotlin
  -- exercises
  -- solutions
  -- tools

Rename the packages (remove the _ from names)

**Comment by ajoz** [comment]
If we would like the tools to be a separate entity for example a standalone library, we would need them to be as a separate project. For example:
- java (directory containing a project)
  - exercies (module)
  - solutions (module)
  - tools (module)

It would be nice to:
- build exercies
- build solutions and run tests for them
- build tools, run tests and deploy to jcenter

**Comment by AlexZhukovich** [comment]
I propose to create a new ticket for configuring CI as a separate issue.
@ajoz What do you think about it?

**Comment by ajoz** [comment]
@AlexZhukovich I've created an issue https://github.com/foobaz42/fp-workshop-jvm/issues/19
